name: lbs
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flutter_login: ^1.0.10+1
  flutter_speed_dial: ^1.2.5
  font_awesome_flutter: ^8.5.0
  floating_search_bar: ^0.2.0
  http: ^0.12.0+2
  flutter_plugin_pdf_viewer: ^1.0.7
  #path_provider: ^1.5.1
  modal_progress_hud: ^0.1.3
  firebase_database: ^3.1.1
  barcode_scan: ^1.0.0
  shared_preferences: ^0.5.6
  provider: ^3.1.0
  file_picker: ^1.4.3+2
  sqflite: ^1.2.0
  open_file: ^2.1.1
  #for finding path of sdcard
  path_provider: ^1.5.1
  #for constructing path of sdcard
  path: ^1.6.4
#  animated_text_kit: ^1.3.0
#firebase_auth: ^0.15.3
#  firebase_core: ^0.4.3+1
#  cloud_firestore: ^0.13.0+1
#  modal_progress_hud: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/
    - pdf/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito/Nunito-ExtraBold.ttf
          weight: 900
        - asset: assets/fonts/Nunito/Nunito-Bold.ttf
          weight: 800
        - asset: assets/fonts/Nunito/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/Nunito/Nunito-ExtraLight.ttf
          weight: 200